# Generated by Django 5.1.5 on 2025-01-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenMRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resonancia', models.ImageField(upload_to='resonancias/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(default='Unknown', max_length=100)),
                ('prediction_probability', models.DecimalField(decimal_places=3, max_digits=6)),
                ('prediction_confidence', models.DecimalField(decimal_places=3, max_digits=6)),
                ('prediction_entropy', models.DecimalField(decimal_places=3, max_digits=6)),
                ('resonancia_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predicciones.imagenmri')),
            ],
        ),
    ]
