# Generated by Django 5.1.5 on 2025-02-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
